# -- 코드를 입력하세요
SELECT C.APNT_NO, C.PT_NAME, C.PT_NO, C.MCDP_CD, D.DR_NAME, C.APNT_YMD
FROM
    (SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.APNT_YMD, A.MCDP_CD, A.APNT_CNCL_YN, A.MDDR_ID 
    FROM APPOINTMENT A
    JOIN PATIENT B
    ON A.PT_NO = B.PT_NO) C
    JOIN DOCTOR D
    ON C.MDDR_ID = D.DR_ID
WHERE C.MCDP_CD='CS'AND C.APNT_CNCL_YN = 'N' 
AND DATEDIFF(C.APNT_YMD, '2022-04-13')=0
ORDER BY C.APNT_YMD ASC;